/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#faf8ff",
        "surface-dim": "#d2d9f4",
        "surface-bright": "#faf8ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f2f3ff",
        "surface-container": "#eaedff",
        "surface-container-high": "#e2e7ff",
        "surface-container-highest": "#dae2fd",
        "on-surface": "#131b2e",
        "on-surface-variant": "#414844",
        "inverse-surface": "#283044",
        "inverse-on-surface": "#eef0ff",
        "outline": "#717973",
        "outline-variant": "#c1c8c2",
        "surface-tint": "#3f6653",
        "primary": "#012d1d",
        "on-primary": "#ffffff",
        "primary-container": "#1b4332",
        "on-primary-container": "#86af99",
        "inverse-primary": "#a5d0b9",
        "secondary": "#1c6390",
        "on-secondary": "#ffffff",
        "secondary-container": "#90cdff",
        "on-secondary-container": "#025783",
        "tertiary": "#2d2519",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#443b2d",
        "on-tertiary-container": "#b2a593",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#c1ecd4",
        "primary-fixed-dim": "#a5d0b9",
        "on-primary-fixed": "#002114",
        "on-primary-fixed-variant": "#274e3d",
        "secondary-fixed": "#cbe6ff",
        "secondary-fixed-dim": "#90cdff",
        "on-secondary-fixed": "#001e31",
        "on-secondary-fixed-variant": "#004b72",
        "tertiary-fixed": "#efe0cd",
        "tertiary-fixed-dim": "#d2c4b2",
        "on-tertiary-fixed": "#221a0f",
        "on-tertiary-fixed-variant": "#4f4538",
        "background": "#faf8ff",
        "on-background": "#131b2e",
        "surface-variant": "#dae2fd"
      },
      borderRadius: {
        "sm": "0.25rem",
        "DEFAULT": "0.5rem",
        "md": "0.75rem",
        "lg": "1rem",
        "xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "base": "8px",
        "xs": "4px",
        "sm": "12px",
        "md": "24px",
        "lg": "48px",
        "xl": "80px",
        "gutter": "24px",
        "margin-mobile": "16px",
        "margin-desktop": "64px"
      },
      fontFamily: {
        "headline-xl": ["Epilogue"],
        "headline-lg": ["Epilogue"],
        "headline-md": ["Epilogue"],
        "body-lg": ["Epilogue"],
        "body-md": ["Epilogue"],
        "label-bold": ["Epilogue"],
        "headline-lg-mobile": ["Epilogue"]
      },
      fontSize: {
        "headline-xl": ["48px", { lineHeight: "56px", fontWeight: "800", letterSpacing: "-0.02em" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "700", letterSpacing: "-0.01em" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-bold": ["14px", { lineHeight: "20px", fontWeight: "700" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "700" }]
      }
    },
  },
  plugins: [],
}
