export default function TermsPage() {
  return (
    <div className="pt-[100px] md:pt-[120px] pb-24 md:pb-xl px-5 md:px-lg max-w-[800px] mx-auto w-full">
      <h1 className="font-display-sm md:font-display-md text-primary mb-6">Terms of Service</h1>
      
      <div className="bg-surface-container-low rounded-2xl p-md md:p-lg shadow-sm space-y-8">
        <section>
          <h2 className="font-headline-sm text-secondary mb-3">1. Acceptance of Terms</h2>
          <p className="font-body-md text-on-surface-variant leading-relaxed">
            By accessing and using Tuklas, you accept and agree to be bound by the terms and provision of this agreement. If you do not agree to abide by these terms, please do not use this service.
          </p>
        </section>

        <section>
          <h2 className="font-headline-sm text-secondary mb-3">2. Description of Service</h2>
          <p className="font-body-md text-on-surface-variant leading-relaxed">
            Tuklas is an AI-powered travel planning tool designed specifically for the Philippines. It generates suggested itineraries based on user inputs. These itineraries are suggestions only and do not constitute actual bookings, reservations, or guarantees of availability.
          </p>
        </section>

        <section>
          <h2 className="font-headline-sm text-secondary mb-3">3. User Responsibilities</h2>
          <p className="font-body-md text-on-surface-variant leading-relaxed">
            You are responsible for verifying all travel information independently. Tuklas does not book flights, accommodations, or activities. You must ensure you have the necessary travel documents, visas, and meet all entry requirements for the Philippines.
          </p>
        </section>

        <section>
          <h2 className="font-headline-sm text-secondary mb-3">4. Disclaimer of Warranties</h2>
          <p className="font-body-md text-on-surface-variant leading-relaxed">
            The information provided by Tuklas is for general informational purposes only. While we strive to keep information accurate and up-to-date, we make no representations or warranties of any kind, express or implied, about the completeness, accuracy, reliability, or availability of the destinations or activities suggested.
          </p>
        </section>
        
        <section>
          <h2 className="font-headline-sm text-secondary mb-3">5. Limitation of Liability</h2>
          <p className="font-body-md text-on-surface-variant leading-relaxed">
            In no event shall Tuklas be liable for any direct, indirect, incidental, consequential, or special damages arising out of or in connection with your use of the service or reliance on any itinerary generated by our AI.
          </p>
        </section>

        <div className="pt-4 border-t border-outline-variant/30 text-label-md text-on-surface-variant">
          Last updated: {new Date().toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}
        </div>
      </div>
    </div>
  );
}
