-- Schema for Tuklas Database

-- Enable UUID generation extension if not exists
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. Create destinations table
CREATE TABLE IF NOT EXISTS destinations (
  id SERIAL PRIMARY KEY,
  island_group VARCHAR(50) NOT NULL, -- 'Luzon', 'Visayas', 'Mindanao'
  region_name VARCHAR(100) NOT NULL,
  hub_name VARCHAR(100) NOT NULL UNIQUE,
  category VARCHAR(50) NOT NULL,
  is_hidden_gem BOOLEAN DEFAULT FALSE,
  description TEXT,
  image_url TEXT,
  vibes TEXT[],
  activities TEXT[]
);

-- 2. Create saved_itineraries table
CREATE TABLE IF NOT EXISTS saved_itineraries (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  hub_name VARCHAR(100) NOT NULL,
  duration_days INT NOT NULL,
  purpose VARCHAR(100) NOT NULL,
  pace VARCHAR(50) NOT NULL,
  itinerary_data JSONB NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 3. Seed destinations data
INSERT INTO destinations (island_group, region_name, hub_name, category, is_hidden_gem, description, image_url, vibes, activities) VALUES
('Luzon', 'National Capital Region', 'Metro Manila', 'Sightseeing', false, 'Historic Intramuros, dynamic BGC urban environments, and diverse culinary districts.', NULL, ARRAY['Food Trip', 'Shopping', 'Heritage & Culture'], ARRAY['Explore the historic walled city of Intramuros', 'Dine at top-rated restaurants in BGC and Makati', 'Shop at mega-malls like SM Mall of Asia', 'Visit the National Museum complex']),
('Luzon', 'Cordillera Administrative Region', 'Baguio City', 'Sightseeing', false, 'Cool mountain climate, pine forests, artistic cafes, and local craft markets.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Baguio_city_proper_overlooking_Burnham-Harrison_side_%28Baguio_city%3B_12-04-2022%29.jpg/330px-Baguio_city_proper_overlooking_Burnham-Harrison_side_%28Baguio_city%3B_12-04-2022%29.jpg', ARRAY['Relaxation', 'Food Trip', 'Heritage & Culture'], ARRAY['Stroll through Burnham Park and Camp John Hay', 'Pick fresh strawberries in La Trinidad', 'Visit the BenCab Museum', 'Shop for local crafts at the Night Market']),
('Luzon', 'Cordillera Administrative Region', 'Cordillera Highlands (Sagada/Banaue)', 'Sightseeing', true, 'Ancient rice terraces, hanging coffins, and mystical mountain caves.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Banaue-terrace.JPG/330px-Banaue-terrace.JPG', ARRAY['Adventure', 'Heritage & Culture', 'Wellness'], ARRAY['Marvel at the Banaue Rice Terraces', 'Explore the Sumaguing Cave in Sagada', 'View the hanging coffins at Echo Valley', 'Hike up Mt. Kiltepan for sunrise']),
('Luzon', 'MIMAROPA', 'Palawan (El Nido/Coron)', 'Sightseeing', false, 'World-class limestone karst formations, lagoons, and crystal clear diving ecosystems.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/El_Nido_Bay_December_2018.jpg/330px-El_Nido_Bay_December_2018.jpg', ARRAY['Adventure', 'Relaxation'], ARRAY['Take an underground river tour in Puerto Princesa', 'Island hop in El Nido''s Bacuit Bay', 'Snorkel at Kayangan Lake in Coron', 'Explore World War II shipwrecks']),
('Luzon', 'Cagayan Valley', 'Batanes', 'Sightseeing', true, 'Rolling green hills, traditional stone houses, and deep Pacific ocean cliffs.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/Sabtang_Batanes.jpg/330px-Sabtang_Batanes.jpg', ARRAY['Relaxation', 'Heritage & Culture'], ARRAY['Cycle through the rolling hills of Marlboro Country', 'Visit the iconic Basco Lighthouse', 'Explore the traditional stone houses in Sabtang', 'Enjoy fresh coconut crab and local delicacies']),
('Visayas', 'Western Visayas', 'Boracay Island', 'Sightseeing', false, 'Powder-white sand beaches, active water sports, and energetic island nightlife.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Boracay_White_Beach.png/330px-Boracay_White_Beach.png', ARRAY['Relaxation', 'Adventure', 'Food Trip'], ARRAY['Watch the iconic sunset at White Beach', 'Try kite surfing at Bulabog Beach', 'Go helmet diving or parasailing', 'Experience the vibrant nightlife at Station 2']),
('Visayas', 'Western Visayas', 'Iloilo & Guimaras', 'Eating', false, 'Historic Spanish churches, iconic batchoy noodle soups, and exceptionally sweet mangoes.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Mandurriao_Iloilo_City_skyline_2025_%28enhanced%29.jpg/330px-Mandurriao_Iloilo_City_skyline_2025_%28enhanced%29.jpg', ARRAY['Food Trip', 'Heritage & Culture', 'Relaxation'], ARRAY['Taste authentic La Paz Batchoy at the public market', 'Visit centuries-old churches like Miag-ao', 'Take a quick boat ride to Guimaras for sweet mangoes', 'Walk along the Iloilo River Esplanade']),
('Visayas', 'Western Visayas', 'Bacolod City', 'Eating', false, 'The City of Smiles, sugarcane heritage mansions, and authentic chicken inasal.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/San_Sebastian_Cathedral_Bacolod_%28Rizal_Street%2C_Bacolod%2C_Negros_Occidental%3B_10-31-2022%29.jpg/330px-San_Sebastian_Cathedral_Bacolod_%28Rizal_Street%2C_Bacolod%2C_Negros_Occidental%3B_10-31-2022%29.jpg', ARRAY['Food Trip', 'Heritage & Culture'], ARRAY['Tour the majestic Ruins of Talisay', 'Eat authentic chicken inasal', 'Visit the Silay heritage houses', 'Experience the MassKara Festival vibe (if visiting in October)']),
('Visayas', 'Central Visayas', 'Cebu (City, Moalboal, Bantayan)', 'Sightseeing', false, 'Rich historical markers, massive sardine runs, and white sand northern beaches.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Cebu_City_2026_skyline1.jpg/330px-Cebu_City_2026_skyline1.jpg', ARRAY['Adventure', 'Food Trip', 'Relaxation'], ARRAY['Swim with sardine runs in Moalboal', 'Canyoneer at Kawasan Falls', 'Visit Magellan''s Cross and Basilica Minore del Santo Niño', 'Relax on the white sands of Bantayan Island']),
('Visayas', 'Central Visayas', 'Bohol (Panglao & Chocolate Hills)', 'Sightseeing', false, 'Unique conical geological structures, tarsier wildlife sanctuaries, and diving resorts.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Chocolate_Hills_Bohol.JPG/330px-Chocolate_Hills_Bohol.JPG', ARRAY['Adventure', 'Relaxation', 'Heritage & Culture'], ARRAY['View the famous Chocolate Hills', 'Take a Loboc River cruise with a buffet lunch', 'Spot the tiny Philippine Tarsiers', 'Relax on Alona Beach in Panglao']),
('Visayas', 'Central Visayas', 'Dumaguete & Siquijor', 'Sightseeing', true, 'Relaxed university coastal town paired with a mystical island of multi-tiered falls.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Dumaguete_Belfry_park_view_%28Perdices_Street%2C_Dumaguete%2C_Negros_Oriental%3B_01-19-2023%29.jpg/330px-Dumaguete_Belfry_park_view_%28Perdices_Street%2C_Dumaguete%2C_Negros_Oriental%3B_01-19-2023%29.jpg', ARRAY['Relaxation', 'Adventure', 'Wellness'], ARRAY['Stroll along the Rizal Boulevard in Dumaguete', 'Dive at Apo Island marine sanctuary', 'Explore the mystical Balete tree in Siquijor', 'Jump into the Cambugahay Falls']),
('Visayas', 'Eastern Visayas', 'Leyte (Kalanggaman Island)', 'Sightseeing', true, 'Pristine, narrow sandbars isolated in highly transparent turquoise waters.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Kalanggaman_Island.jpg/330px-Kalanggaman_Island.jpg', ARRAY['Relaxation', 'Adventure'], ARRAY['Walk along the famous Kalanggaman sandbar', 'Cross the San Juanico Bridge', 'Visit the MacArthur Landing Memorial National Park', 'Dive or snorkel in clear island waters']),
('Visayas', 'Eastern Visayas', 'Samar Eco-Adventure Hub', 'Sightseeing', true, 'Massive underground cave configurations and raw river trekking corridors.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Samar_Island_Location_Map_Red.png/330px-Samar_Island_Location_Map_Red.png', ARRAY['Adventure'], ARRAY['Navigate the extreme rapids on a Torpedo Boat ride', 'Explore the massive caves of Sohoton Natural Bridge', 'Swim in the cold pools of Lulugayan Falls', 'Try the Basey mat weaving']),
('Mindanao', 'Zamboanga Peninsula', 'Zamboanga City', 'Sightseeing', true, 'Rich Hispanic-Chavacano historic fort settings and rare pink coralline sand shores.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/Zamboanga_City_Hall_%26_Rizal_Park%2C_Mar_2026.jpg/330px-Zamboanga_City_Hall_%26_Rizal_Park%2C_Mar_2026.jpg', ARRAY['Heritage & Culture', 'Food Trip'], ARRAY['Visit the colorful vinta boats at Paseo del Mar', 'Relax on the pink sands of Great Santa Cruz Island', 'Shop at the Barter Trade Market', 'Eat Curacha with Alavar sauce']),
('Mindanao', 'Zamboanga Peninsula', 'Dapitan & Dakak', 'Sightseeing', true, 'Historical exile grounds of Dr. Jose Rizal and secure coastal resort basins.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Dapitan_Church_facade.jpg/330px-Dapitan_Church_facade.jpg', ARRAY['Heritage & Culture', 'Relaxation'], ARRAY['Visit the historical Jose Rizal Shrine', 'Enjoy the rides at Gloria''s Fantasyland', 'Relax at the luxurious Dakak Beach Resort', 'Stroll along the Dapitan Boulevard']),
('Mindanao', 'Northern Mindanao', 'Cagayan de Oro City', 'Sightseeing', false, 'The white water rafting capital of the Philippines and major urban trading node.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/CDO_Poblacion%2C_CM_Recto_Avenue-A._Velez%2C_Misamis_Oriental_Provincial_Capitol_drone_%28Cagayan_De_Oro_City%3B_03-21-2026%29.jpg/330px-CDO_Poblacion%2C_CM_Recto_Avenue-A._Velez%2C_Misamis_Oriental_Provincial_Capitol_drone_%28Cagayan_De_Oro_City%3B_03-21-2026%29.jpg', ARRAY['Adventure', 'Food Trip'], ARRAY['Go extreme whitewater rafting on the Cagayan de Oro River', 'Visit the Macahambus Cave and Gorge', 'Enjoy the thrills at Seven Seas Waterpark', 'Explore the Mapawa Nature Park']),
('Mindanao', 'Northern Mindanao', 'Bukidnon Highlands', 'Sightseeing', true, 'Pine ridges, cool alpine atmosphere, rolling hills, and extreme zipline clusters.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Mt._Kalatungan_Sunrise.jpg/330px-Mt._Kalatungan_Sunrise.jpg', ARRAY['Adventure', 'Relaxation'], ARRAY['Experience thrills at Dahilayan Adventure Park', 'Visit the vast Del Monte Pineapple Plantation', 'Hike up Mt. Dulang-Dulang or Mt. Kitanglad', 'Enjoy the cool mountain climate at local cafes']),
('Mindanao', 'Northern Mindanao', 'Camiguin Island', 'Sightseeing', false, 'Volcanic island escape featuring natural hot/cold springs and sunken cemetery landmarks.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Timpoong_and_Hibok-Hibok_Natural_Monument_in_Camiguin_-_Allan_Jay_Quesada.jpg/330px-Timpoong_and_Hibok-Hibok_Natural_Monument_in_Camiguin_-_Allan_Jay_Quesada.jpg', ARRAY['Adventure', 'Relaxation'], ARRAY['Visit the Sunken Cemetery at sunset', 'Lounge on the pristine White Island sandbar', 'Swim in the cold springs of Santo Niño', 'Hike the slopes of Mt. Hibok-Hibok']),
('Mindanao', 'Davao Region', 'Davao City & Samal Island', 'Sightseeing', false, 'Progressive eco-city housing Mt. Apo, rich fruit markets, and nearby beach getaways.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Davao_Poblacion_District_skyline_Bajada_%28Davao_City%3B_08-22-2023%29.jpg/330px-Davao_Poblacion_District_skyline_Bajada_%28Davao_City%3B_08-22-2023%29.jpg', ARRAY['Food Trip', 'Relaxation', 'Adventure'], ARRAY['Visit the Philippine Eagle Center', 'Eat fresh durian at Magsaysay Park', 'Take a ferry to the beautiful beaches of Samal Island', 'Hike the foothills of Mt. Apo']),
('Mindanao', 'Davao Region', 'Mati (Dahican Beach)', 'Sightseeing', true, 'Crescent white-sand shoreline famous for skimboarding and marine mammal tracking.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Flag_of_Mati%2C_Davao_Oriental.png/330px-Flag_of_Mati%2C_Davao_Oriental.png', ARRAY['Adventure', 'Relaxation'], ARRAY['Surf and skimboard at Dahican Beach', 'Fly in an ultralight plane over the coast', 'Visit the Sleeping Dinosaur Island viewpoint', 'Spot sea turtles along the bay']),
('Mindanao', 'SOCCSKSARGEN', 'Lake Sebu (South Cotabato)', 'Sightseeing', true, 'Cultural cradle of the Tboli tribe featuring serene lotus lakes and traditional weaving loops.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/LakeSebuSunset_01.jpg/330px-LakeSebuSunset_01.jpg', ARRAY['Heritage & Culture', 'Relaxation', 'Adventure'], ARRAY['Ride the 7 Falls Zipline', 'Cruise along Lake Sebu on a traditional boat', 'Learn T''boli culture and T''nalak weaving', 'Eat fresh tilapia dishes']),
('Mindanao', 'SOCCSKSARGEN', 'General Santos City', 'Eating', false, 'The premier tuna terminal capital hosting vibrant fresh deep-sea seafood culinary tracking.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Gensan_Dadiangas_South%2C_P._Acharon_Boulevard%2C_Gensan_Public_Market_drone_%28General_Santos_City%3B_03-24-2026%29.jpg/330px-Gensan_Dadiangas_South%2C_P._Acharon_Boulevard%2C_Gensan_Public_Market_drone_%28General_Santos_City%3B_03-24-2026%29.jpg', ARRAY['Food Trip'], ARRAY['Visit the bustling GenSan Fish Port Complex', 'Eat the freshest tuna sashimi', 'Trek to the peak of Sanchez Peak', 'Explore the local weaving communities']),
('Mindanao', 'Caraga', 'Siargao Island', 'Sightseeing', false, 'Globally recognized surfing epicenters with aesthetic palm-fringed lifestyle dynamics.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Siargao_Island%2C_PH%2C_Sentinel-2.jpg/330px-Siargao_Island%2C_PH%2C_Sentinel-2.jpg', ARRAY['Adventure', 'Relaxation', 'Wellness'], ARRAY['Surf the legendary Cloud 9 waves', 'Island hop to Naked, Daku, and Guyam Islands', 'Swing on palm trees at the Maasin River', 'Explore the Magpupungko Rock Pools']),
('Mindanao', 'Caraga', 'Surigao del Sur (Hinatuan/Bislig)', 'Sightseeing', true, 'The deep blue, crystal clear Enchanted River and multi-tiered wide waterfalls.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Hinatuan_enchanted_river.jpg/330px-Hinatuan_enchanted_river.jpg', ARRAY['Adventure', 'Relaxation'], ARRAY['Swim in the crystal clear Hinatuan Enchanted River', 'Marvel at the massive Tinuy-an Falls', 'Island hop in Britania Group of Islands', 'Eat fresh seafood at local markets']),
('Mindanao', 'BARMM', 'Tawi-Tawi (Bongao)', 'Sightseeing', true, 'Untouched stilt-village communities, ancient mountain peaks, and deep heritage mosques.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Panguan_Island.jpg/330px-Panguan_Island.jpg', ARRAY['Heritage & Culture', 'Adventure'], ARRAY['Hike Bud Bongao and feed the friendly macaques', 'Visit the oldest mosque in the Philippines (Sheik Makdum)', 'Buy fresh seafood at the local Badjao market', 'Explore untouched pristine beaches'])
ON CONFLICT (hub_name) DO UPDATE SET
  island_group = EXCLUDED.island_group,
  region_name = EXCLUDED.region_name,
  category = EXCLUDED.category,
  is_hidden_gem = EXCLUDED.is_hidden_gem,
  description = EXCLUDED.description,
  image_url = EXCLUDED.image_url,
  vibes = EXCLUDED.vibes,
  activities = EXCLUDED.activities;

-- Additional newly researched destinations
INSERT INTO destinations (island_group, region_name, hub_name, category, is_hidden_gem, description, image_url, vibes, activities) VALUES
('Luzon', 'Ilocos Region', 'Vigan City', 'Sightseeing', false, 'Well-preserved 16th-century Spanish colonial town with cobblestone streets and heritage houses.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Allan_Jay_Quesada_-_Vigan_Cathedral_001.jpg/960px-Allan_Jay_Quesada_-_Vigan_Cathedral_001.jpg', ARRAY['Heritage & Culture', 'Relaxation', 'Food Trip'], ARRAY['Walk along the cobblestone streets of Calle Crisologo', 'Try authentic Vigan Longganisa and Empanada', 'Visit the Baluarte Resort and Mini Zoo', 'Watch the dancing fountain at Plaza Salcedo']),
('Luzon', 'Ilocos Region', 'La Union (San Juan)', 'Sightseeing', false, 'The surfing capital of Northern Luzon, known for its vibrant beach culture and sunset cafes.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Surf%E2%80%99s_up.jpg/960px-Surf%E2%80%99s_up.jpg', ARRAY['Adventure', 'Relaxation', 'Food Trip'], ARRAY['Learn to surf at Urbiztondo Beach', 'Go cafe-hopping along the coastal strip', 'Visit the Tangadan Falls in San Gabriel', 'Watch the vibrant sunset over the West Philippine Sea']),
('Luzon', 'Central Luzon', 'Baler, Aurora', 'Sightseeing', false, 'Historic coastal town featuring the birthplace of Philippine surfing and scenic waterfalls.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Siargao_Island%2C_PH%2C_Sentinel-2.jpg/330px-Siargao_Island%2C_PH%2C_Sentinel-2.jpg', ARRAY['Adventure', 'Heritage & Culture', 'Relaxation'], ARRAY['Surf the waves at Sabang Beach', 'Hike to the majestic Ditumabo Mother Falls', 'Visit the historic Baler Church', 'Climb the giant Balete tree']),
('Luzon', 'Central Luzon', 'Zambales (Subic & San Antonio)', 'Sightseeing', false, 'Ash-covered beaches from Mt. Pinatubo, pine trees, and accessible shipwreck diving.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Subic_Municipal_Hall%2C_Zambales%2C_Aug_2025_%281%29.jpg/960px-Subic_Municipal_Hall%2C_Zambales%2C_Aug_2025_%281%29.jpg', ARRAY['Adventure', 'Relaxation'], ARRAY['Camp at Anawangin or Nagsasa Cove', 'Explore the Subic Bay shipwreck dive sites', 'Go duty-free shopping in Subic', 'Trek to the crater of Mt. Pinatubo']),
('Luzon', 'CALABARZON', 'Tagaytay City', 'Eating', false, 'Cool climate ridge-town offering panoramic views of Taal Volcano and famous bulalo soup.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Tagaytay_Highlands%2C_Philippines_%28lulaymb%29_3_-_Flickr.jpg/960px-Tagaytay_Highlands%2C_Philippines_%28lulaymb%29_3_-_Flickr.jpg', ARRAY['Relaxation', 'Food Trip'], ARRAY['Enjoy the panoramic view of Taal Volcano', 'Eat hot Bulalo at Mahogany Market', 'Have a fun day at Sky Ranch', 'Visit the Caleruega Church for a peaceful retreat']),
('Luzon', 'CALABARZON', 'Batangas (Anilao & Laiya)', 'Sightseeing', false, 'World-renowned muck diving sites and accessible white-sand resort coves.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Muelle_Port%2C_Puerto_Galera%2C_Oriental_Mindoro%2C_April_2023.jpg/960px-Muelle_Port%2C_Puerto_Galera%2C_Oriental_Mindoro%2C_April_2023.jpg', ARRAY['Adventure', 'Relaxation'], ARRAY['Scuba dive in the marine sanctuaries of Anilao', 'Relax on the white sands of Laiya', 'Hike up Mt. Maculot for stunning views', 'Taste the famous Batangas Lomi']),
('Luzon', 'MIMAROPA', 'Puerto Galera', 'Sightseeing', false, 'Vibrant coastal town with diverse marine biodiversity, waterfalls, and bustling nightlife.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Muelle_Port%2C_Puerto_Galera%2C_Oriental_Mindoro%2C_April_2023.jpg/960px-Muelle_Port%2C_Puerto_Galera%2C_Oriental_Mindoro%2C_April_2023.jpg', ARRAY['Adventure', 'Relaxation', 'Food Trip'], ARRAY['Dive the vibrant coral reefs of Sabang', 'Relax at White Beach', 'Trek to the Tamaraw Waterfalls', 'Enjoy the coastal nightlife']),
('Luzon', 'Bicol Region', 'Legazpi City (Albay)', 'Sightseeing', false, 'Home to the perfectly cone-shaped Mayon Volcano, spicy Bicolano cuisine, and ATV adventures.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Mount_Mayon_Cagsawa_field_view_close-up_%28Busay%2C_Daraga%2C_Albay%3B_04-21-2023%29.jpg/960px-Mount_Mayon_Cagsawa_field_view_close-up_%28Busay%2C_Daraga%2C_Albay%3B_04-21-2023%29.jpg', ARRAY['Adventure', 'Food Trip', 'Heritage & Culture'], ARRAY['Ride an ATV around the base of Mayon Volcano', 'Visit the historic Cagsawa Ruins', 'Try the spicy Bicol Express and Sili Ice Cream', 'Explore the Sumlang Lake on a bamboo raft']),
('Luzon', 'Bicol Region', 'Sorsogon (Donsol)', 'Sightseeing', true, 'Eco-tourism hotspot famous for ethical whale shark interactions and firefly river cruises.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Donsol_-Philippines_-_panoramio.jpg/960px-Donsol_-Philippines_-_panoramio.jpg', ARRAY['Adventure', 'Relaxation'], ARRAY['Swim with the gentle whale sharks', 'Take a firefly watching river cruise', 'Relax at the pink sand beach of Subic (Matnog)', 'Explore the Bulusan Volcano Natural Park']),
('Visayas', 'Western Visayas', 'Antique', 'Sightseeing', true, 'Rugged eco-adventure province offering kawa hot baths, river tubing, and majestic rice terraces.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Tibiao%2C_Antique_%28P._Martin%29_-_Flickr.jpg/960px-Tibiao%2C_Antique_%28P._Martin%29_-_Flickr.jpg', ARRAY['Adventure', 'Wellness', 'Relaxation'], ARRAY['Take a relaxing dip in a Kawa hot bath', 'Go river tubing at Bugang River', 'Visit the Malalison Island sandbar', 'Hike the Antique Rice Terraces']),
('Visayas', 'Western Visayas', 'Capiz', 'Eating', true, 'The seafood capital of the Philippines, offering fresh oysters, crabs, and historical river tours.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Sta_Monica_Church.jpg/960px-Sta_Monica_Church.jpg', ARRAY['Food Trip', 'Heritage & Culture'], ARRAY['Indulge in a massive seafood feast in Roxas City', 'Take the Palina Greenbelt River Cruise', 'Visit the historical Panay Church', 'Learn about local mythology and folklore']),
('Visayas', 'Western Visayas', 'Sipalay (Negros Occidental)', 'Sightseeing', true, 'Stunning sugar beach resorts, sunken ship diving spots, and islet-dotted marine reserves.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Pump_boat_in_Sipalay.jpg/960px-Pump_boat_in_Sipalay.jpg', ARRAY['Relaxation', 'Adventure'], ARRAY['Watch the sunset at Sugar Beach', 'Explore the Perth Paradise Resort islets', 'Dive the sunken shipwrecks in the bay', 'Relax at the quiet Punta Ballo beach']),
('Visayas', 'Central Visayas', 'Malapascua Island', 'Sightseeing', true, 'World-famous diving destination offering daily encounters with rare pelagic thresher sharks.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Dumaguete_Belfry_park_view_%28Perdices_Street%2C_Dumaguete%2C_Negros_Oriental%3B_01-19-2023%29.jpg/330px-Dumaguete_Belfry_park_view_%28Perdices_Street%2C_Dumaguete%2C_Negros_Oriental%3B_01-19-2023%29.jpg', ARRAY['Adventure', 'Relaxation'], ARRAY['Dive to see the rare Thresher Sharks at Monad Shoal', 'Relax on the pristine Bounty Beach', 'Take a boat to Kalanggaman Island for a day trip', 'Snorkel the Japanese shipwreck dive sites']),
('Visayas', 'Eastern Visayas', 'Biliran', 'Sightseeing', true, 'An undiscovered island province boasting numerous majestic waterfalls, hot springs, and terraced landscapes.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Cebu_City_2026_skyline1.jpg/330px-Cebu_City_2026_skyline1.jpg', ARRAY['Adventure', 'Relaxation'], ARRAY['Swim in the multi-tiered Tinago Falls', 'Relax in the Mainit Hot Springs', 'Island hop to Sambawan Island', 'Marvel at the Iyusan Rice Terraces']),
('Visayas', 'Eastern Visayas', 'Southern Leyte', 'Sightseeing', true, 'Pristine marine sanctuaries, historic first mass site, and uncrowded whale shark sightings.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Kalanggaman_Island.jpg/330px-Kalanggaman_Island.jpg', ARRAY['Adventure', 'Heritage & Culture'], ARRAY['Dive in the pristine waters of Sogod Bay', 'Look for seasonal whale sharks', 'Visit the First Mass site at Limasawa Island', 'Explore the Napantao Marine Sanctuary']),
('Mindanao', 'Northern Mindanao', 'Iligan City', 'Sightseeing', false, 'The City of Majestic Waterfalls, featuring the iconic Maria Cristina Falls and Tinago Falls.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Cebu_City_2026_skyline1.jpg/330px-Cebu_City_2026_skyline1.jpg', ARRAY['Adventure', 'Relaxation'], ARRAY['Marvel at the powerful Maria Cristina Falls', 'Swim in the turquoise waters of Tinago Falls', 'Visit the Mimbalot Falls', 'Try the local Iligan Lechon']),
('Mindanao', 'Caraga', 'Dinagat Islands', 'Sightseeing', true, 'Mystical island province with dramatic limestone cliffs, secret lagoons, and unique local culture.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/El_Nido_Bay_December_2018.jpg/330px-El_Nido_Bay_December_2018.jpg', ARRAY['Adventure', 'Relaxation'], ARRAY['Explore the secret lagoons and limestone formations', 'Visit the mystical PBMA shrine', 'Relax on the white sands of Bitaog Beach', 'Discover the tidal pools at Pangabangan Island']),
('Mindanao', 'BARMM', 'Cotabato City', 'Sightseeing', true, 'Cultural melting pot housing the majestic Grand Mosque and the historic Tamontaka Church.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/Zamboanga_City_Hall_%26_Rizal_Park%2C_Mar_2026.jpg/330px-Zamboanga_City_Hall_%26_Rizal_Park%2C_Mar_2026.jpg', ARRAY['Heritage & Culture', 'Food Trip'], ARRAY['Visit the majestic Sultan Haji Hassanal Bolkiah Mosque', 'Explore the historical Tamontaka Church', 'See the intricate brassware at the local markets', 'Try the traditional Maguindanaon pastil']),
('Mindanao', 'BARMM', 'Basilan (Malamawi Island)', 'Sightseeing', true, 'An emerging tourism frontier boasting the pristine, white-sand Malamawi Beach.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Boracay_White_Beach.png/330px-Boracay_White_Beach.png', ARRAY['Relaxation', 'Adventure'], ARRAY['Relax on the pristine white sands of Malamawi Beach', 'Experience the local Yakan weaving culture', 'Taste fresh seafood caught by local fishermen', 'Take a scenic boat ride around the coastal villages'])
ON CONFLICT (hub_name) DO UPDATE SET
  island_group = EXCLUDED.island_group,
  region_name = EXCLUDED.region_name,
  category = EXCLUDED.category,
  is_hidden_gem = EXCLUDED.is_hidden_gem,
  description = EXCLUDED.description,
  -- By putting 'destinations.column' first, we ensure that if your live database 
  -- ALREADY has an image, vibe, or activity, it won't be overwritten by the seed script.
  -- It will only use the seed data if the database currently has NULL.
  image_url = COALESCE(destinations.image_url, EXCLUDED.image_url),
  vibes = COALESCE(destinations.vibes, EXCLUDED.vibes),
  activities = COALESCE(destinations.activities, EXCLUDED.activities);

-- 4. Updates for advanced caching
ALTER TABLE saved_itineraries 
  ADD COLUMN IF NOT EXISTS cache_key CHAR(64),
  ADD COLUMN IF NOT EXISTS budget VARCHAR(50),
  ADD COLUMN IF NOT EXISTS travel_group VARCHAR(100),
  ADD COLUMN IF NOT EXISTS accommodation VARCHAR(50),
  ADD COLUMN IF NOT EXISTS dietary VARCHAR(200),
  ADD COLUMN IF NOT EXISTS notes TEXT,
  ADD COLUMN IF NOT EXISTS expires_at TIMESTAMP;

-- 5. Safe column additions for destinations (for existing databases)
--    CREATE TABLE IF NOT EXISTS won't add new columns if the table already exists.
ALTER TABLE destinations
  ADD COLUMN IF NOT EXISTS vibes TEXT[],
  ADD COLUMN IF NOT EXISTS activities TEXT[];

-- Indexes for performance
CREATE UNIQUE INDEX IF NOT EXISTS idx_cache_key 
  ON saved_itineraries (cache_key);
CREATE INDEX IF NOT EXISTS idx_expires_at 
  ON saved_itineraries (expires_at);
CREATE INDEX IF NOT EXISTS idx_destinations_island 
  ON destinations (island_group);
-- GIN index enables efficient array lookups (e.g., WHERE 'Adventure' = ANY(vibes))
CREATE INDEX IF NOT EXISTS idx_destinations_vibes
  ON destinations USING GIN (vibes);
